### PR TITLE
Fix month view force unwrap crash

### PR DESCRIPTION
**Pull request by robertcrabtree**
I think this should do it

### CODE REVIEW

**Review by jznadams — COMMENTED** [review]
I thought there was a lot more than this: https://github.com/TapInspect/JTAppleCalendar_OLD/commit/df6aa918d0cddfe6f48c52f967237e24d66f504a

 Or are you doing this across multiple PRs?

**Comment by robertcrabtree** [comment]
You are right. Man, this is really confusing. I'm bouncing around 4 different repos. I just cherry-picked the commit. I hope this is all of the stuff

**Comment by robertcrabtree** [comment]
I just tested this PR with tap inspect on the main branch. We should be good to merge.

**Comment by jznadams** [comment]
Missed one: https://github.com/TapInspect/JTAppleCalendar_OLD/commit/3edf8fba3d9314ff5e42626c945031668e54dd47

https://github.com/TapInspect/JTAppleCalendar_OLD/pull/4

**Comment by robertcrabtree** [comment]
Dude, it's already included in this PR. It's the first commit.

**Review by jznadams — APPROVED** [review]

**Pull request merged**
